import numpy as np
import raven_utils.properties as properties
import raven_utils.group as group


SLOT_TRANSFORMATION_NO = 4
PROPERTY_TRANSFORMATION_NO = 8
PROPERTIES_TRANSFORMATION_NO = PROPERTY_TRANSFORMATION_NO * properties.NO
PROPERTIES_TRANSFORMATION_SIZE = PROPERTIES_TRANSFORMATION_NO * group.NO

SLOT_TRANSFORMATION_SIZE = PROPERTY_TRANSFORMATION_NO * group.NO
SIZE = SLOT_TRANSFORMATION_SIZE + PROPERTIES_TRANSFORMATION_SIZE

SLOT_SLICE = np.s_[:, :SLOT_TRANSFORMATION_SIZE]
PROPERTIES_SLICE = np.s_[:, -PROPERTIES_TRANSFORMATION_SIZE:]
